"use strict";(()=>{var e={};e.id=5274,e.ids=[5274],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},24433:(e,t,s)=>{s.r(t),s.d(t,{originalPathname:()=>g,patchFetch:()=>R,requestAsyncStorage:()=>m,routeModule:()=>c,serverHooks:()=>x,staticGenerationAsyncStorage:()=>f});var r={};s.r(r),s.d(r,{GET:()=>l,POST:()=>p,dynamic:()=>d});var n=s(49303),a=s(88716),i=s(60670),o=s(87070),u=s(90455);let d="force-dynamic";async function l(e){let t=(0,u.f)(),{data:{session:s}}=await t.auth.getSession();if(!s)return o.NextResponse.json({error:"Unauthorized"},{status:401});let{data:r}=await t.from("profiles").select("role").eq("id",s.user.id).single();if(!r||"admin"!==r.role)return o.NextResponse.json({error:"Forbidden"},{status:403});let{searchParams:n}=new URL(e.url),a=n.get("user_id");if(!a)return o.NextResponse.json({error:"user_id is required"},{status:400});let{data:i,error:d}=await t.from("user_items").select(`
      id,
      name,
      quantity,
      notes,
      created_at,
      updated_at,
      event:events (
        id,
        title
      )
    `).eq("user_id",a).order("updated_at",{ascending:!1});return d?o.NextResponse.json({error:d.message},{status:500}):o.NextResponse.json({items:i||[]})}async function p(e){let t=(0,u.f)(),{data:{session:s}}=await t.auth.getSession();if(!s)return o.NextResponse.json({error:"Unauthorized"},{status:401});let{data:r}=await t.from("profiles").select("role").eq("id",s.user.id).single();if(!r||"admin"!==r.role)return o.NextResponse.json({error:"Forbidden"},{status:403});let{user_id:n,name:a,quantity:i,event_id:d,notes:l}=await e.json();if(!n||!a||void 0===i)return o.NextResponse.json({error:"user_id, name, and quantity are required"},{status:400});let{data:p,error:c}=await t.from("user_items").insert({user_id:n,name:a,quantity:parseInt(i),event_id:d||null,notes:l||null}).select().single();return c?o.NextResponse.json({error:c.message},{status:500}):o.NextResponse.json({item:p},{status:201})}let c=new n.AppRouteRouteModule({definition:{kind:a.x.APP_ROUTE,page:"/api/admin/items/route",pathname:"/api/admin/items",filename:"route",bundlePath:"app/api/admin/items/route"},resolvedPagePath:"/Users/alan_dingchaoliao/Documents/網站開發/網站架設/app/api/admin/items/route.ts",nextConfigOutput:"",userland:r}),{requestAsyncStorage:m,staticGenerationAsyncStorage:f,serverHooks:x}=c,g="/api/admin/items/route";function R(){return(0,i.patchFetch)({serverHooks:x,staticGenerationAsyncStorage:f})}},90455:(e,t,s)=>{s.d(t,{createAdminSupabaseClient:()=>l,f:()=>d});var r=s(71615),n=s(67721),a=s(43974);let i="https://wlomyjuuqovdatrxrfpu.supabase.co",o="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsb215anV1cW92ZGF0cnhyZnB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NDg2MzEsImV4cCI6MjA3ODUyNDYzMX0.Wkdwi0TKCfkYmKYCfFd6WrkbieTwQ07wf_yxuANVifY",u=process.env.SUPABASE_SERVICE_ROLE_KEY??"";function d(){let e=(0,r.cookies)();return(0,n.createServerClient)(i,o,{cookies:{get:t=>e.get(t)?.value,set(t,s,r){try{e.set({name:t,value:s,...r})}catch{}},remove(t,s){try{e.set({name:t,value:"",...s})}catch{}}}})}function l(){return u?(0,a.eI)(i,u,{auth:{autoRefreshToken:!1,persistSession:!1}}):(console.warn("⚠️ SUPABASE_SERVICE_ROLE_KEY is not set. Admin operations may fail due to RLS policies."),console.warn("Please set SUPABASE_SERVICE_ROLE_KEY environment variable in Vercel."),(0,a.eI)(i,o,{auth:{autoRefreshToken:!1,persistSession:!1}}))}}};var t=require("../../../../webpack-runtime.js");t.C(e);var s=e=>t(t.s=e),r=t.X(0,[8948,9576,9702,5972],()=>s(24433));module.exports=r})();