"use strict";(()=>{var e={};e.id=9060,e.ids=[9060],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},99648:(e,r,t)=>{t.r(r),t.d(r,{originalPathname:()=>w,patchFetch:()=>k,requestAsyncStorage:()=>m,routeModule:()=>p,serverHooks:()=>f,staticGenerationAsyncStorage:()=>g});var i={};t.r(i),t.d(i,{GET:()=>u,POST:()=>c,dynamic:()=>d});var n=t(49303),a=t(88716),o=t(60670),s=t(87070),_=t(90455);let d="force-dynamic",l={tier_12:{name:"12天獎勵",requiredStreak:12,requiredPoints:null,allowedGenerations:[9],description:"連續簽到 12 天可選擇第 9 世代寶可夢 或 抽獎券"},tier_40:{name:"40天獎勵",requiredStreak:40,requiredPoints:null,allowedGenerations:[7,8,9],description:"連續簽到 40 天可選擇第 7-9 世代寶可夢"},tier_points:{name:"積分獎勵",requiredStreak:null,requiredPoints:120,allowedGenerations:[6,7,8,9],description:"累積 120 幸運點數可選擇第 6-9 世代寶可夢 或 $1000 盲盒抵用卷"}};async function u(e){let r=(0,_.f)(),{data:{user:t}}=await r.auth.getUser();if(!t)return s.NextResponse.json({error:"Unauthorized"},{status:401});let{data:i}=await r.from("profiles").select(`
            check_in_streak,
            fortune_points,
            reward_tier_12_goal_id,
            reward_tier_12_claimed_at,
            reward_tier_40_goal_id,
            reward_tier_40_claimed_at,
            reward_tier_points_goal_id,
            reward_tier_points_claimed_at
        `).eq("id",t.id).single(),n=i?.check_in_streak||0,a=i?.fortune_points||0,{searchParams:o}=new URL(e.url),d=o.get("tier"),u={tier_12:{...l.tier_12,unlocked:n>=12,goalId:i?.reward_tier_12_goal_id,claimedAt:i?.reward_tier_12_claimed_at,canSelect:!i?.reward_tier_12_goal_id&&n>=12,progress:Math.min(n,12),target:12},tier_40:{...l.tier_40,unlocked:n>=40,goalId:i?.reward_tier_40_goal_id,claimedAt:i?.reward_tier_40_claimed_at,canSelect:!i?.reward_tier_40_goal_id&&n>=40,progress:Math.min(n,40),target:40},tier_points:{...l.tier_points,unlocked:a>=120,goalId:i?.reward_tier_points_goal_id,claimedAt:i?.reward_tier_points_claimed_at,canSelect:!i?.reward_tier_points_goal_id&&a>=120,progress:Math.min(a,120),target:120}},c=null;if(d&&l[d]){let e=l[d],{data:t}=await r.from("distributions").select("id, pokemon_name, pokemon_name_en, pokemon_sprite_url, is_shiny, generation, original_trainer, event_name").in("generation",e.allowedGenerations).order("generation",{ascending:!0}).order("pokemon_name",{ascending:!0}),i=t||[];if("tier_12"===d){let{data:e}=await r.from("distributions").select("id, pokemon_name, pokemon_name_en, pokemon_sprite_url, is_shiny, generation, original_trainer, event_name").eq("id","00000000-0000-0000-0000-000000000001");e&&e.length>0&&(i=[...e,...i])}else if("tier_points"===d){let{data:e}=await r.from("distributions").select("id, pokemon_name, pokemon_name_en, pokemon_sprite_url, is_shiny, generation, original_trainer, event_name").eq("id","00000000-0000-0000-0000-000000000002");e&&e.length>0&&(i=[...e,...i])}c=i}let p=[i?.reward_tier_12_goal_id,i?.reward_tier_40_goal_id,i?.reward_tier_points_goal_id].filter(Boolean),m={};if(p.length>0){let{data:e}=await r.from("distributions").select("id, pokemon_name, pokemon_sprite_url, is_shiny, event_name").in("id",p);e&&(m=Object.fromEntries(e.map(e=>[e.id,e])))}return s.NextResponse.json({tiers:u,distributions:c,goalDistributions:m,currentStreak:n,currentPoints:a})}async function c(e){let r=(0,_.f)(),{data:{user:t}}=await r.auth.getUser();if(!t)return s.NextResponse.json({error:"Unauthorized"},{status:401});try{let{tier:i,distributionId:n}=await e.json();if(!i||!l[i])return s.NextResponse.json({error:"無效的獎勵層級"},{status:400});if(!n)return s.NextResponse.json({error:"請選擇一個寶可夢"},{status:400});let{data:a}=await r.from("profiles").select(`
                check_in_streak,
                fortune_points,
                reward_tier_12_goal_id,
                reward_tier_40_goal_id,
                reward_tier_points_goal_id
            `).eq("id",t.id).single();if(!a)return s.NextResponse.json({error:"找不到用戶資料"},{status:404});let o=`reward_${i}_goal_id`;if(a[o])return s.NextResponse.json({error:"此層級已設定目標，無法變更。如需變更請聯繫管理員。"},{status:400});let _=l[i];if(_.requiredStreak&&a.check_in_streak<_.requiredStreak)return s.NextResponse.json({error:`需要連續簽到 ${_.requiredStreak} 天才能解鎖此獎勵`},{status:400});if(_.requiredPoints&&(a.fortune_points||0)<_.requiredPoints)return s.NextResponse.json({error:`需要累積 ${_.requiredPoints} 幸運點數才能解鎖此獎勵`},{status:400});let{data:d,error:u}=await r.from("distributions").select("id, pokemon_name, generation").eq("id",n).single();if(u||!d)return s.NextResponse.json({error:"找不到指定的配布"},{status:404});if(!_.allowedGenerations.includes(d.generation))return s.NextResponse.json({error:`此層級只能選擇第 ${_.allowedGenerations.join("、")} 世代的寶可夢`},{status:400});let c={};c[o]=n;let{error:p}=await r.from("profiles").update(c).eq("id",t.id);if(p)return console.error("Update goal error:",p),s.NextResponse.json({error:"設定失敗，請稍後再試"},{status:500});return s.NextResponse.json({success:!0,message:`已將 ${_.name} 目標設定為 ${d.pokemon_name}！此選擇無法變更。`,distribution:d})}catch{return s.NextResponse.json({error:"無效的請求"},{status:400})}}let p=new n.AppRouteRouteModule({definition:{kind:a.x.APP_ROUTE,page:"/api/check-in/goal/route",pathname:"/api/check-in/goal",filename:"route",bundlePath:"app/api/check-in/goal/route"},resolvedPagePath:"/Users/alan_dingchaoliao/Documents/網站開發/網站架設/app/api/check-in/goal/route.ts",nextConfigOutput:"",userland:i}),{requestAsyncStorage:m,staticGenerationAsyncStorage:g,serverHooks:f}=p,w="/api/check-in/goal/route";function k(){return(0,o.patchFetch)({serverHooks:f,staticGenerationAsyncStorage:g})}},90455:(e,r,t)=>{t.d(r,{createAdminSupabaseClient:()=>l,f:()=>d});var i=t(71615),n=t(67721),a=t(43974);let o="https://wlomyjuuqovdatrxrfpu.supabase.co",s="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsb215anV1cW92ZGF0cnhyZnB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NDg2MzEsImV4cCI6MjA3ODUyNDYzMX0.Wkdwi0TKCfkYmKYCfFd6WrkbieTwQ07wf_yxuANVifY",_=process.env.SUPABASE_SERVICE_ROLE_KEY??"";function d(){let e=(0,i.cookies)();return(0,n.createServerClient)(o,s,{cookies:{get:r=>e.get(r)?.value,set(r,t,i){try{e.set({name:r,value:t,...i})}catch{}},remove(r,t){try{e.set({name:r,value:"",...t})}catch{}}}})}function l(){return _?(0,a.eI)(o,_,{auth:{autoRefreshToken:!1,persistSession:!1}}):(console.warn("⚠️ SUPABASE_SERVICE_ROLE_KEY is not set. Admin operations may fail due to RLS policies."),console.warn("Please set SUPABASE_SERVICE_ROLE_KEY environment variable in Vercel."),(0,a.eI)(o,s,{auth:{autoRefreshToken:!1,persistSession:!1}}))}}};var r=require("../../../../webpack-runtime.js");r.C(e);var t=e=>r(r.s=e),i=r.X(0,[8948,9576,9702,5972],()=>t(99648));module.exports=i})();