"use strict";(()=>{var e={};e.id=9440,e.ids=[9440],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},58243:(e,t,a)=>{a.r(t),a.d(t,{originalPathname:()=>x,patchFetch:()=>y,requestAsyncStorage:()=>c,routeModule:()=>l,serverHooks:()=>g,staticGenerationAsyncStorage:()=>_});var n={};a.r(n),a.d(n,{GET:()=>m,dynamic:()=>p});var r=a(49303),s=a(88716),i=a(60670),o=a(87070),d=a(90455),u=a(86727);let p="force-dynamic";async function m(){let e=(0,d.f)(),{data:{user:t}}=await e.auth.getUser();if(!t)return o.NextResponse.json({error:"Unauthorized"},{status:401});let a=new Date,n=new Date(u.J.startDate),r=new Date(u.J.endDate),s=new Date;s.setHours(0,0,0,0);let i=new Date(s);i.setDate(i.getDate()+1);let{count:p}=await e.from("eevee_day_quiz_attempts").select("*",{count:"exact",head:!0}).eq("user_id",t.id).gte("attempted_at",s.toISOString()).lt("attempted_at",i.toISOString()),{count:m}=await e.from("eevee_day_stamps").select("*",{count:"exact",head:!0}).eq("user_id",t.id),{data:l}=await e.from("eevee_day_rewards").select(`
            id,
            distribution_id,
            selected_at,
            distributions (
                id,
                pokemon_name,
                pokemon_name_en,
                pokemon_sprite_url,
                is_shiny,
                generation,
                event_name,
                original_trainer
            )
        `).eq("user_id",t.id).single(),c=[];if((m||0)>=u.J.stampsRequired&&!l){let{data:t}=await e.from("distributions").select("id, pokemon_name, pokemon_name_en, pokemon_sprite_url, is_shiny, generation, event_name, original_trainer").in("generation",u.J.allowedGenerations).in("pokemon_name",u.J.allowedPokemon).order("pokemon_name");c=t||[]}let _=a.toDateString()===r.toDateString(),g=_&&6===(m||0),x=g?3:u.J.dailyAttempts;return o.NextResponse.json({isActive:a>=n&&a<=r,hasEnded:a>r,startDate:u.J.startDate,endDate:u.J.endDate,stamps:m||0,stampsRequired:u.J.stampsRequired,attemptsToday:p||0,dailyAttempts:x,remainingAttempts:Math.max(0,x-(p||0)),hasRetakeTicket:g,isLastDay:_,reward:l||null,availableDistributions:c})}let l=new r.AppRouteRouteModule({definition:{kind:s.x.APP_ROUTE,page:"/api/eevee-day/status/route",pathname:"/api/eevee-day/status",filename:"route",bundlePath:"app/api/eevee-day/status/route"},resolvedPagePath:"/Users/alan_dingchaoliao/Documents/網站開發/網站架設/app/api/eevee-day/status/route.ts",nextConfigOutput:"",userland:n}),{requestAsyncStorage:c,staticGenerationAsyncStorage:_,serverHooks:g}=l,x="/api/eevee-day/status/route";function y(){return(0,i.patchFetch)({serverHooks:g,staticGenerationAsyncStorage:_})}}};var t=require("../../../../webpack-runtime.js");t.C(e);var a=e=>t(t.s=e),n=t.X(0,[8948,9576,9702,5972,1809],()=>a(58243));module.exports=n})();