// 伊布寶可夢 Day 問答題庫
// 約 100 題，涵蓋：基礎知識、遊戲機制、傳說/幻獸、動畫/電影、配布歷史、伊布特輯

export type Question = {
    id: number;
    question: string;
    options: string[];
    answer: number; // 正確選項的 index (0-3)
    category: string;
};

export const QUESTIONS: Question[] = [
    // ========== 基礎知識 (20 題) ==========
    {
        id: 1,
        question: "寶可夢世界中，火屬性對哪個屬性有效果拔群？",
        options: ["水", "草", "地面", "岩石"],
        answer: 1,
        category: "基礎知識",
    },
    {
        id: 2,
        question: "寶可夢共有幾種屬性？",
        options: ["15", "16", "17", "18"],
        answer: 3,
        category: "基礎知識",
    },
    {
        id: 3,
        question: "皮卡丘是什麼屬性的寶可夢？",
        options: ["一般", "電", "妖精", "草"],
        answer: 1,
        category: "基礎知識",
    },
    {
        id: 4,
        question: "第一世代的御三家草屬性寶可夢是？",
        options: ["妙蛙種子", "菊草葉", "木守宮", "草苗龜"],
        answer: 0,
        category: "基礎知識",
    },
    {
        id: 5,
        question: "龍屬性對哪個屬性完全無效？",
        options: ["鋼", "妖精", "冰", "一般"],
        answer: 1,
        category: "基礎知識",
    },
    {
        id: 6,
        question: "一般屬性的招式對哪個屬性無效？",
        options: ["鋼", "岩石", "幽靈", "暗"],
        answer: 2,
        category: "基礎知識",
    },
    {
        id: 7,
        question: "哪個屬性對鋼屬性有效果拔群？",
        options: ["草", "火", "電", "冰"],
        answer: 1,
        category: "基礎知識",
    },
    {
        id: 8,
        question: "寶可夢最多可以學會幾個招式？",
        options: ["3", "4", "5", "6"],
        answer: 1,
        category: "基礎知識",
    },
    {
        id: 9,
        question: "第二世代新增了哪兩個屬性？",
        options: ["妖精和龍", "暗和鋼", "蟲和飛行", "冰和格鬥"],
        answer: 1,
        category: "基礎知識",
    },
    {
        id: 10,
        question: "妖精屬性是在第幾世代新增的？",
        options: ["第四世代", "第五世代", "第六世代", "第七世代"],
        answer: 2,
        category: "基礎知識",
    },
    {
        id: 11,
        question: "寶可夢進化時，哪個條件最常見？",
        options: ["攜帶道具", "等級提升", "通信交換", "親密度"],
        answer: 1,
        category: "基礎知識",
    },
    {
        id: 12,
        question: "地面屬性對電屬性的效果是？",
        options: ["效果拔群", "效果一般", "效果不佳", "完全無效"],
        answer: 0,
        category: "基礎知識",
    },
    {
        id: 13,
        question: "冰屬性對龍屬性的效果是？",
        options: ["完全無效", "效果不佳", "效果一般", "效果拔群"],
        answer: 3,
        category: "基礎知識",
    },
    {
        id: 14,
        question: "超夢是第幾世代的寶可夢？",
        options: ["第一世代", "第二世代", "第三世代", "第四世代"],
        answer: 0,
        category: "基礎知識",
    },
    {
        id: 15,
        question: "毒屬性對以下哪個屬性效果拔群？",
        options: ["地面", "岩石", "妖精", "火"],
        answer: 2,
        category: "基礎知識",
    },
    {
        id: 16,
        question: "飛行屬性的弱點不包括以下哪個？",
        options: ["電", "冰", "火", "岩石"],
        answer: 2,
        category: "基礎知識",
    },
    {
        id: 17,
        question: "第三世代的火屬性御三家是？",
        options: ["小火龍", "火雉雞", "火球鼠", "暖暖豬"],
        answer: 1,
        category: "基礎知識",
    },
    {
        id: 18,
        question: "格鬥屬性對一般屬性效果是？",
        options: ["完全無效", "效果不佳", "效果一般", "效果拔群"],
        answer: 3,
        category: "基礎知識",
    },
    {
        id: 19,
        question: "寶可夢對戰中，先攻的決定因素主要是？",
        options: ["攻擊力", "防禦力", "速度", "HP"],
        answer: 2,
        category: "基礎知識",
    },
    {
        id: 20,
        question: "水屬性對以下哪個屬性效果不佳？",
        options: ["火", "地面", "草", "岩石"],
        answer: 2,
        category: "基礎知識",
    },

    // ========== 遊戲機制 (15 題) ==========
    {
        id: 21,
        question: "寶可夢的個體值（IV）最高是多少？",
        options: ["15", "25", "31", "50"],
        answer: 2,
        category: "遊戲機制",
    },
    {
        id: 22,
        question: "寶可夢有幾個主要能力值？",
        options: ["4", "5", "6", "7"],
        answer: 2,
        category: "遊戲機制",
    },
    {
        id: 23,
        question: "太陽天氣下，哪個屬性的招式威力增強？",
        options: ["水", "草", "火", "電"],
        answer: 2,
        category: "遊戲機制",
    },
    {
        id: 24,
        question: "屬性一致加成（STAB）的倍率是多少？",
        options: ["1.2 倍", "1.5 倍", "2.0 倍", "1.3 倍"],
        answer: 1,
        category: "遊戲機制",
    },
    {
        id: 25,
        question: "寶可夢的性格共有幾種？",
        options: ["20", "25", "30", "15"],
        answer: 1,
        category: "遊戲機制",
    },
    {
        id: 26,
        question: "Mega 進化是從第幾世代開始的？",
        options: ["第五世代", "第六世代", "第七世代", "第八世代"],
        answer: 1,
        category: "遊戲機制",
    },
    {
        id: 27,
        question: "太晶化（Terastallize）是哪個世代引入的？",
        options: ["第七世代", "第八世代", "第九世代", "第六世代"],
        answer: 2,
        category: "遊戲機制",
    },
    {
        id: 28,
        question: "Z 招式是從第幾世代開始的？",
        options: ["第六世代", "第七世代", "第八世代", "第九世代"],
        answer: 1,
        category: "遊戲機制",
    },
    {
        id: 29,
        question: "極巨化（Dynamax）是哪個世代的機制？",
        options: ["第七世代", "第八世代", "第九世代", "第六世代"],
        answer: 1,
        category: "遊戲機制",
    },
    {
        id: 30,
        question: "雨天時，哪個屬性的招式威力下降？",
        options: ["水", "電", "火", "草"],
        answer: 2,
        category: "遊戲機制",
    },
    {
        id: 31,
        question: "親密度進化最有名的寶可夢之一是？",
        options: ["皮卡丘", "伊布", "小火龍", "波克比"],
        answer: 3,
        category: "遊戲機制",
    },
    {
        id: 32,
        question: "努力值（EV）單項最高可以累積到多少？",
        options: ["200", "252", "255", "300"],
        answer: 1,
        category: "遊戲機制",
    },
    {
        id: 33,
        question: "寶可夢的異色（色違）機率在沒有加成的情況下是？",
        options: ["1/1000", "1/2048", "1/4096", "1/8192"],
        answer: 2,
        category: "遊戲機制",
    },
    {
        id: 34,
        question: "特性「威嚇」的效果是什麼？",
        options: ["提升自身攻擊", "降低對方攻擊", "提高速度", "降低對方速度"],
        answer: 1,
        category: "遊戲機制",
    },
    {
        id: 35,
        question: "天氣「沙暴」會持續傷害哪些屬性以外的寶可夢？",
        options: ["地面、岩石、鋼", "火、地面、岩石", "岩石、鋼、水", "地面、火、鋼"],
        answer: 0,
        category: "遊戲機制",
    },

    // ========== 傳說/幻獸 (20 題) ==========
    {
        id: 36,
        question: "以下哪隻是幻之寶可夢？",
        options: ["超夢", "夢幻", "蓋歐卡", "烈空坐"],
        answer: 1,
        category: "傳說/幻獸",
    },
    {
        id: 37,
        question: "帕路奇亞掌管的是什麼？",
        options: ["時間", "空間", "反物質", "自然"],
        answer: 1,
        category: "傳說/幻獸",
    },
    {
        id: 38,
        question: "帝牙盧卡掌管的是什麼？",
        options: ["空間", "時間", "夢境", "生命"],
        answer: 1,
        category: "傳說/幻獸",
    },
    {
        id: 39,
        question: "騎拉帝納棲息在哪個世界？",
        options: ["現實世界", "毀壞的世界", "超空間", "夢世界"],
        answer: 1,
        category: "傳說/幻獸",
    },
    {
        id: 40,
        question: "阿爾宙斯被稱為什麼？",
        options: ["時間之神", "創造之神", "海洋之王", "天空霸主"],
        answer: 1,
        category: "傳說/幻獸",
    },
    {
        id: 41,
        question: "哪隻傳說寶可夢是朱版的封面寶可夢？",
        options: ["故勒頓", "密勒頓", "奈克洛茲瑪", "蒼響"],
        answer: 0,
        category: "傳說/幻獸",
    },
    {
        id: 42,
        question: "蒼響和藏瑪然特是哪個世代的傳說寶可夢？",
        options: ["第七世代", "第八世代", "第九世代", "第六世代"],
        answer: 1,
        category: "傳說/幻獸",
    },
    {
        id: 43,
        question: "達克萊伊是什麼屬性的幻之寶可夢？",
        options: ["超能力", "幽靈", "暗", "毒"],
        answer: 2,
        category: "傳說/幻獸",
    },
    {
        id: 44,
        question: "比克提尼的專屬招式是？",
        options: ["V熱焰", "聖火", "噴火", "火焰驅進"],
        answer: 0,
        category: "傳說/幻獸",
    },
    {
        id: 45,
        question: "三神柱指的是哪三隻寶可夢？",
        options: ["雷吉洛克、雷吉艾斯、雷吉斯奇魯", "固拉多、蓋歐卡、烈空坐", "帝牙盧卡、帕路奇亞、騎拉帝納", "雷公、炎帝、水君"],
        answer: 0,
        category: "傳說/幻獸",
    },
    {
        id: 46,
        question: "鳳王和洛奇亞分別是哪個版本的封面寶可夢？",
        options: ["紅/藍", "金/銀", "紅寶石/藍寶石", "鑽石/珍珠"],
        answer: 1,
        category: "傳說/幻獸",
    },
    {
        id: 47,
        question: "哲爾尼亞斯是什麼屬性？",
        options: ["妖精", "暗", "超能力", "龍"],
        answer: 0,
        category: "傳說/幻獸",
    },
    {
        id: 48,
        question: "以下哪隻不屬於「湖之三神」？",
        options: ["由克希", "艾姆利特", "亞克諾姆", "克雷色利亞"],
        answer: 3,
        category: "傳說/幻獸",
    },
    {
        id: 49,
        question: "奈克洛茲瑪與哪隻寶可夢合體後會變成「日蝕」型態？",
        options: ["露奈雅拉", "索爾迦雷歐", "科斯莫古", "烈空坐"],
        answer: 1,
        category: "傳說/幻獸",
    },
    {
        id: 50,
        question: "比克提尼的全國圖鑑編號是多少？",
        options: ["000", "494", "649", "151"],
        answer: 0,
        category: "傳說/幻獸",
    },
    {
        id: 51,
        question: "謝米的「天空型態」是什麼屬性？",
        options: ["草", "草/飛行", "飛行/妖精", "草/超能力"],
        answer: 1,
        category: "傳說/幻獸",
    },
    {
        id: 52,
        question: "基拉祈每隔多少年會醒來一次？",
        options: ["100 年", "500 年", "1000 年", "10 年"],
        answer: 2,
        category: "傳說/幻獸",
    },
    {
        id: 53,
        question: "瑪納霏的專屬招式是？",
        options: ["醒覺力量", "親密無間", "心之水滴", "愛心印記"],
        answer: 2,
        category: "傳說/幻獸",
    },
    {
        id: 54,
        question: "蓋諾賽克特是哪個屬性組合？",
        options: ["蟲/鋼", "蟲/格鬥", "鋼/超能力", "蟲/暗"],
        answer: 0,
        category: "傳說/幻獸",
    },
    {
        id: 55,
        question: "固拉多的原始回歸後是什麼屬性？",
        options: ["地面", "地面/火", "火/岩石", "地面/岩石"],
        answer: 1,
        category: "傳說/幻獸",
    },

    // ========== 動畫/電影 (15 題) ==========
    {
        id: 56,
        question: "小智的皮卡丘為什麼不願意進精靈球？",
        options: ["精靈球壞了", "不喜歡待在精靈球裡", "從未被收服", "是別人的寶可夢"],
        answer: 1,
        category: "動畫/電影",
    },
    {
        id: 57,
        question: "小智的第一隻正式收服的寶可夢是？",
        options: ["綠毛蟲", "比比鳥", "傑尼龜", "小火龍"],
        answer: 0,
        category: "動畫/電影",
    },
    {
        id: 58,
        question: "火箭隊的口號中，武藏和小次郎代表的是？",
        options: ["正義與邪惡", "愛與真實", "力量與速度", "智慧與勇氣"],
        answer: 1,
        category: "動畫/電影",
    },
    {
        id: 59,
        question: "小智在哪個地區首次獲得聯盟冠軍？",
        options: ["豐緣地區", "神奧地區", "阿羅拉地區", "合眾地區"],
        answer: 2,
        category: "動畫/電影",
    },
    {
        id: 60,
        question: "第一部寶可夢劇場版的主角傳說寶可夢是？",
        options: ["洛奇亞", "超夢", "夢幻", "帝牙盧卡"],
        answer: 1,
        category: "動畫/電影",
    },
    {
        id: 61,
        question: "動畫中喵喵會說人話的原因是？",
        options: ["天生能力", "為了追求母喵喵而學的", "被科學家改造", "使用翻譯機"],
        answer: 1,
        category: "動畫/電影",
    },
    {
        id: 62,
        question: "「寶可夢：乘風破浪」的主角名字是？",
        options: ["小智", "莉可", "小光", "小遙"],
        answer: 1,
        category: "動畫/電影",
    },
    {
        id: 63,
        question: "小智的甲賀忍蛙擁有什麼特殊能力？",
        options: ["Mega 進化", "牽絆變身", "Z 招式", "極巨化"],
        answer: 1,
        category: "動畫/電影",
    },
    {
        id: 64,
        question: "在劇場版中，達克萊伊守護的城鎮叫什麼？",
        options: ["帷幕市", "白楊鎮", "阿拉莫斯鎮", "神和鎮"],
        answer: 2,
        category: "動畫/電影",
    },
    {
        id: 65,
        question: "小智最終在世界錦標賽中擊敗了誰成為冠軍？",
        options: ["大吾", "竹蘭", "丹帝", "赤紅"],
        answer: 2,
        category: "動畫/電影",
    },
    {
        id: 66,
        question: "動畫中小智的噴火龍最初不聽話的原因是？",
        options: ["等級太高", "小智徽章不夠", "性格倔強", "受過傷"],
        answer: 1,
        category: "動畫/電影",
    },
    {
        id: 67,
        question: "寶可夢動畫中，火箭隊的喵喵會說人話，但不會使用哪個招式？",
        options: ["憤怒", "亂抓", "聚寶功", "喵喵亂咬"],
        answer: 2,
        category: "動畫/電影",
    },
    {
        id: 68,
        question: "比克提尼出現在哪部劇場版電影？",
        options: ["夢幻與波導的勇者", "比克提尼與黑英雄", "光環的超魔神", "破壞之繭"],
        answer: 1,
        category: "動畫/電影",
    },
    {
        id: 69,
        question: "大木博士的孫子在動畫中叫什麼名字？",
        options: ["小茂", "小智", "赤紅", "阿弘"],
        answer: 0,
        category: "動畫/電影",
    },
    {
        id: 70,
        question: "小智的皮卡丘在第一集遇到的傳說寶可夢是？",
        options: ["夢幻", "洛奇亞", "鳳王", "雪拉比"],
        answer: 2,
        category: "動畫/電影",
    },

    // ========== 配布歷史 (10 題) ==========
    {
        id: 71,
        question: "寶可夢配布的序號通常可以在哪裡輸入？",
        options: ["寶可夢中心", "神秘禮物", "精靈球工廠", "對戰塔"],
        answer: 1,
        category: "配布歷史",
    },
    {
        id: 72,
        question: "「十萬伏特皮卡丘」是指什麼？",
        options: ["一般皮卡丘", "戴著帽子的特殊皮卡丘", "閃光皮卡丘", "極巨化皮卡丘"],
        answer: 1,
        category: "配布歷史",
    },
    {
        id: 73,
        question: "配布寶可夢通常會附帶什麼特殊標記？",
        options: ["特殊精靈球", "經典緞帶", "閃光標誌", "特殊OT名稱"],
        answer: 1,
        category: "配布歷史",
    },
    {
        id: 74,
        question: "寶可夢中心限定配布通常需要什麼？",
        options: ["購買特定商品", "親自到店面", "網路註冊", "預約抽選"],
        answer: 1,
        category: "配布歷史",
    },
    {
        id: 75,
        question: "哪隻寶可夢是最常被當作電影配布的？",
        options: ["皮卡丘", "夢幻", "超夢", "路卡利歐"],
        answer: 0,
        category: "配布歷史",
    },
    {
        id: 76,
        question: "GTS 是什麼系統的縮寫？",
        options: ["Global Trade Station", "Game Trade System", "General Trading Service", "Global Transfer Station"],
        answer: 0,
        category: "配布歷史",
    },
    {
        id: 77,
        question: "寶可夢 HOME 是用於什麼目的的服務？",
        options: ["對戰排名", "寶可夢寄存和交換", "線上購物", "觀看動畫"],
        answer: 1,
        category: "配布歷史",
    },
    {
        id: 78,
        question: "以下哪個不是寶可夢配布的常見方式？",
        options: ["序號配布", "網路配布", "實體店面配布", "電話配布"],
        answer: 3,
        category: "配布歷史",
    },
    {
        id: 79,
        question: "寶可夢日（Pokémon Day）是哪一天？",
        options: ["1 月 1 日", "2 月 27 日", "7 月 7 日", "12 月 25 日"],
        answer: 1,
        category: "配布歷史",
    },
    {
        id: 80,
        question: "寶可夢系列第一款遊戲發售的年份是？",
        options: ["1994", "1995", "1996", "1997"],
        answer: 2,
        category: "配布歷史",
    },

    // ========== 伊布特輯 (20 題) ==========
    {
        id: 81,
        question: "伊布目前共有幾種進化型態？",
        options: ["6 種", "7 種", "8 種", "9 種"],
        answer: 2,
        category: "伊布特輯",
    },
    {
        id: 82,
        question: "伊布使用雷之石會進化成？",
        options: ["水伊布", "火伊布", "雷伊布", "冰伊布"],
        answer: 2,
        category: "伊布特輯",
    },
    {
        id: 83,
        question: "以下哪隻不是伊布的進化型？",
        options: ["葉伊布", "冰伊布", "鋼伊布", "太陽伊布"],
        answer: 2,
        category: "伊布特輯",
    },
    {
        id: 84,
        question: "仙子伊布是什麼屬性？",
        options: ["超能力", "一般", "妖精", "飛行"],
        answer: 2,
        category: "伊布特輯",
    },
    {
        id: 85,
        question: "月亮伊布是什麼屬性？",
        options: ["幽靈", "暗", "超能力", "妖精"],
        answer: 1,
        category: "伊布特輯",
    },
    {
        id: 86,
        question: "太陽伊布是什麼屬性？",
        options: ["火", "超能力", "光（不存在）", "一般"],
        answer: 1,
        category: "伊布特輯",
    },
    {
        id: 87,
        question: "伊布在 Pokémon GO 中，改名為什麼可以進化成水伊布？",
        options: ["Sakura", "Rainer", "Sparky", "Tamao"],
        answer: 1,
        category: "伊布特輯",
    },
    {
        id: 88,
        question: "伊布進化成太陽伊布的條件通常是？",
        options: ["使用太陽石", "白天高親密度進化", "夜晚高親密度進化", "使用光之石"],
        answer: 1,
        category: "伊布特輯",
    },
    {
        id: 89,
        question: "伊布進化成月亮伊布的條件通常是？",
        options: ["使用月之石", "白天高親密度進化", "夜晚高親密度進化", "使用暗之石"],
        answer: 2,
        category: "伊布特輯",
    },
    {
        id: 90,
        question: "伊布進化成仙子伊布的方法是？",
        options: ["使用光之石", "學會妖精招式後升級", "通信交換", "使用月之石"],
        answer: 1,
        category: "伊布特輯",
    },
    {
        id: 91,
        question: "伊布是第幾世代的寶可夢？",
        options: ["第一世代", "第二世代", "第三世代", "第四世代"],
        answer: 0,
        category: "伊布特輯",
    },
    {
        id: 92,
        question: "伊布的全國圖鑑編號是？",
        options: ["125", "133", "143", "150"],
        answer: 1,
        category: "伊布特輯",
    },
    {
        id: 93,
        question: "伊布的日文名字是？",
        options: ["イーブイ", "ピカチュウ", "エーフィ", "ブースター"],
        answer: 0,
        category: "伊布特輯",
    },
    {
        id: 94,
        question: "《Let's Go! 伊布》是哪個平台的遊戲？",
        options: ["3DS", "Nintendo Switch", "Wii U", "Game Boy"],
        answer: 1,
        category: "伊布特輯",
    },
    {
        id: 95,
        question: "伊布在動畫中最常出現的進化型是？",
        options: ["火伊布", "水伊布", "全都差不多", "仙子伊布"],
        answer: 2,
        category: "伊布特輯",
    },
    {
        id: 96,
        question: "伊布的隱藏特性是什麼？",
        options: ["逃跑", "適應力", "危險預知", "魔法鏡"],
        answer: 2,
        category: "伊布特輯",
    },
    {
        id: 97,
        question: "葉伊布是在第幾世代首次出現的？",
        options: ["第二世代", "第三世代", "第四世代", "第五世代"],
        answer: 2,
        category: "伊布特輯",
    },
    {
        id: 98,
        question: "伊布使用火之石會進化成？",
        options: ["雷伊布", "水伊布", "火伊布", "太陽伊布"],
        answer: 2,
        category: "伊布特輯",
    },
    {
        id: 99,
        question: "冰伊布的進化方式是？",
        options: ["使用冰之石", "在冰岩附近升級", "夜晚進化", "通信交換"],
        answer: 1,
        category: "伊布特輯",
    },
    {
        id: 100,
        question: "以下哪隻伊布進化型的速度最高？",
        options: ["火伊布", "雷伊布", "水伊布", "太陽伊布"],
        answer: 1,
        category: "伊布特輯",
    },
];

// 活動設定
export const EEVEE_DAY_CONFIG = {
    eventName: "伊布寶可夢 Day 限時集點",
    startDate: "2026-02-11T00:00:00+08:00",
    endDate: "2026-02-28T23:59:59+08:00",
    dailyAttempts: 2,
    questionsPerQuiz: 10,
    timePerQuestion: 15, // 秒
    passingScore: 7, // 答對 7 題算通過
    stampsRequired: 5, // 集滿 5 點可領取配布
    // 可選配布的篩選條件
    allowedPokemon: ["伊布", "比克提尼", "達克萊伊"],
    allowedGenerations: [8, 9],
};
