// 伊步集點日問答題庫
// 100 題高難度題目，涵蓋：競技對戰、冷門知識、深入配布、遊戲歷史、數據細節、伊布進階

export type Question = {
    id: number;
    question: string;
    options: string[];
    answer: number; // 正確選項的 index (0-3)
    category: string;
};

export const QUESTIONS: Question[] = [
    // ========== 競技對戰 (20 題) ==========
    {
        id: 1,
        question: "在雙打對戰中，招式「守住」連續使用第二次的成功率是多少？",
        options: ["50%", "33%", "25%", "10%"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 2,
        question: "特性「降雨」在第六世代後，天氣效果持續幾回合？",
        options: ["3 回合", "5 回合", "8 回合", "永久"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 3,
        question: "招式「欺詐」的傷害計算是根據什麼？",
        options: ["自身攻擊", "對方攻擊", "自身特攻", "對方特攻"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 4,
        question: "在 VGC 規則中，標準雙打時每邊最多上場幾隻寶可夢？",
        options: ["3", "4", "5", "6"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 5,
        question: "招式「戲法空間」持續幾回合（包含使用當回合）？",
        options: ["3 回合", "4 回合", "5 回合", "6 回合"],
        answer: 2,
        category: "競技對戰",
    },
    {
        id: 6,
        question: "特性「惡作劇之心」在第七世代後對哪個屬性的變化招式無效？",
        options: ["鋼", "暗", "妖精", "超能力"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 7,
        question: "招式「急速折返」的威力是多少？",
        options: ["60", "70", "80", "90"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 8,
        question: "持有道具「講究圍巾」的效果是？",
        options: ["攻擊 ×1.5，只能用一個招式", "速度 ×1.5，只能用一個招式", "特攻 ×1.5，只能用一個招式", "防禦 ×1.5，只能用一個招式"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 9,
        question: "招式「輸出全開」（Over Heat）使用後會降低自身哪項能力兩階？",
        options: ["攻擊", "特攻", "速度", "防禦"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 10,
        question: "特性「天然」的效果是什麼？",
        options: ["無視自身能力變化", "無視對方能力變化", "無視天氣效果", "無視道具效果"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 11,
        question: "招式「滅亡之歌」發動後，幾回合後場上的寶可夢會瀕死？",
        options: ["2 回合", "3 回合", "4 回合", "5 回合"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 12,
        question: "特性「結實」在什麼情況下會失效？",
        options: ["受到連續攻擊招式時", "受到固定傷害時", "HP 不滿時", "以上皆有可能"],
        answer: 3,
        category: "競技對戰",
    },
    {
        id: 13,
        question: "招式「岩石封鎖」除了造成傷害外，還會降低對手什麼能力？",
        options: ["攻擊", "防禦", "速度", "特防"],
        answer: 2,
        category: "競技對戰",
    },
    {
        id: 14,
        question: "道具「氣勢披帶」的效果是什麼？",
        options: ["一定會先攻", "HP 全滿時必定耐住一擊", "提升暴擊率", "免疫異常狀態"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 15,
        question: "特性「蓄電」除了免疫電屬性招式外，還有什麼效果？",
        options: ["提升速度", "回復 HP", "提升特攻", "反彈傷害"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 16,
        question: "招式「先制防守」和「守住」的差異是？",
        options: ["威力不同", "先制防守只擋先制招式", "先制防守可以連續使用", "沒有差異"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 17,
        question: "寶可夢對戰中，暴擊的傷害倍率在第六世代後是多少？",
        options: ["1.25 倍", "1.5 倍", "2.0 倍", "2.5 倍"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 18,
        question: "特性「魔法防守」的效果是？",
        options: ["免疫所有傷害", "只會受到攻擊招式的傷害", "免疫異常狀態", "免疫能力下降"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 19,
        question: "招式「蜻蜓迴轉」是什麼屬性的招式？",
        options: ["飛行", "蟲", "一般", "龍"],
        answer: 1,
        category: "競技對戰",
    },
    {
        id: 20,
        question: "道具「突撃背心」的效果是？",
        options: ["攻擊 ×1.5，不能用變化招式", "特防 ×1.5，不能用變化招式", "防禦 ×1.5，不能用攻擊招式", "速度 ×1.5，不能用先制招式"],
        answer: 1,
        category: "競技對戰",
    },

    // ========== 冷門知識 (20 題) ==========
    {
        id: 21,
        question: "百變怪用「變身」後，唯一不會複製的數值是什麼？",
        options: ["攻擊", "速度", "HP", "特攻"],
        answer: 2,
        category: "冷門知識",
    },
    {
        id: 22,
        question: "寶可夢「脫殼忍者」的 HP 固定是多少？",
        options: ["1", "5", "10", "隨等級變動"],
        answer: 0,
        category: "冷門知識",
    },
    {
        id: 23,
        question: "哪隻寶可夢擁有最多的型態變化？",
        options: ["洛托姆", "阿爾宙斯", "蓋諾賽克特", "碎蛋"],
        answer: 1,
        category: "冷門知識",
    },
    {
        id: 24,
        question: "招式「拍落」除了傷害以外，還有什麼效果？",
        options: ["降低速度", "使對方道具失效", "降低攻擊", "使對方混亂"],
        answer: 1,
        category: "冷門知識",
    },
    {
        id: 25,
        question: "哪隻第一世代寶可夢在初代曾被分類為「恐龍寶可夢」後來改名？",
        options: ["暴鯉龍", "尼多王", "袋獸", "化石翼龍"],
        answer: 2,
        category: "冷門知識",
    },
    {
        id: 26,
        question: "勾魂眼在第六世代之前有什麼特殊之處？",
        options: ["種族值最低", "沒有弱點", "不能進化", "不能被捕捉"],
        answer: 1,
        category: "冷門知識",
    },
    {
        id: 27,
        question: "寶可夢「果然翁」只能學會幾個招式？",
        options: ["2 個", "4 個", "6 個", "8 個"],
        answer: 1,
        category: "冷門知識",
    },
    {
        id: 28,
        question: "「不可思議棒棒糖」的效果是什麼？",
        options: ["提升 10 等級", "提升 1 等級", "回復全部 HP", "提升親密度"],
        answer: 1,
        category: "冷門知識",
    },
    {
        id: 29,
        question: "寶可夢蛋孵化時，遺傳招式是由哪方決定的（第九世代之前）？",
        options: ["只有母方", "只有父方", "父方為主", "隨機決定"],
        answer: 2,
        category: "冷門知識",
    },
    {
        id: 30,
        question: "特性「慢啟動」需要幾回合後才能恢復正常能力？",
        options: ["3 回合", "5 回合", "7 回合", "10 回合"],
        answer: 1,
        category: "冷門知識",
    },
    {
        id: 31,
        question: "寶可夢最高可以到達幾等級？",
        options: ["50", "80", "99", "100"],
        answer: 3,
        category: "冷門知識",
    },
    {
        id: 32,
        question: "哪隻寶可夢是唯一的電/一般屬性組合（在帕底亞圖鑑中）？",
        options: ["電肚蛙", "巴弗特", "光蚪仔", "電龍"],
        answer: 0,
        category: "冷門知識",
    },
    {
        id: 33,
        question: "招式「億萬吸收」的 HP 回復量是傷害的百分之幾？",
        options: ["25%", "50%", "75%", "100%"],
        answer: 2,
        category: "冷門知識",
    },
    {
        id: 34,
        question: "在寶可夢遊戲中，「閃光術」在第幾世代被從秘傳招式中移除？",
        options: ["第五世代", "第六世代", "第七世代", "第四世代"],
        answer: 2,
        category: "冷門知識",
    },
    {
        id: 35,
        question: "鑽石/珍珠的地下通道可以挖到化石，以下哪個化石不是第四世代的？",
        options: ["頭蓋化石", "盾甲化石", "根狀化石", "爪狀化石"],
        answer: 2,
        category: "冷門知識",
    },
    {
        id: 36,
        question: "寶可夢「美納斯」在第三世代的進化條件是什麼？",
        options: ["升級到 30 等", "美麗度達到最高", "通信交換持有美鱗", "使用水之石"],
        answer: 1,
        category: "冷門知識",
    },
    {
        id: 37,
        question: "寶可夢遊戲中，使用招式「催眠術」後對手會睡幾回合（第五世代後）？",
        options: ["1-2 回合", "1-3 回合", "2-4 回合", "2-5 回合"],
        answer: 1,
        category: "冷門知識",
    },
    {
        id: 38,
        question: "以下哪隻寶可夢的種族值總和最高？",
        options: ["超夢", "烈空坐", "Mega 烈空坐", "阿爾宙斯"],
        answer: 2,
        category: "冷門知識",
    },
    {
        id: 39,
        question: "特性「加速」每回合提升什麼能力一階？",
        options: ["攻擊", "特攻", "速度", "迴避率"],
        answer: 2,
        category: "冷門知識",
    },
    {
        id: 40,
        question: "寶可夢遊戲中，最早可以進行線上對戰的是哪個世代？",
        options: ["第三世代", "第四世代", "第五世代", "第六世代"],
        answer: 1,
        category: "冷門知識",
    },

    // ========== 深入配布 (15 題) ==========
    {
        id: 41,
        question: "2014 年的「Diancie 配布」是為了推廣哪部劇場版？",
        options: ["光環的超魔神", "破壞之繭與蒂安希", "波爾凱尼恩與機巧的瑪基亞那", "我們的故事"],
        answer: 1,
        category: "深入配布",
    },
    {
        id: 42,
        question: "配布寶可夢的經典緞帶在遊戲中有什麼作用？",
        options: ["提升經驗值", "防止被交換", "只是標記無實際功能", "解鎖特殊招式"],
        answer: 2,
        category: "深入配布",
    },
    {
        id: 43,
        question: "日本寶可夢中心城市限定配布中，以下哪個城市沒有對應的皮卡丘？",
        options: ["橫濱", "大阪", "札幌", "奈良"],
        answer: 3,
        category: "深入配布",
    },
    {
        id: 44,
        question: "在配布歷史中，「老海」是哪隻配布寶可夢的OT？",
        options: ["夢幻", "超夢", "達克萊伊", "基拉祈"],
        answer: 0,
        category: "深入配布",
    },
    {
        id: 45,
        question: "第一個可以透過 Wi-Fi 下載的全球配布寶可夢是？",
        options: ["夢幻", "達克萊伊", "瑪納霏", "阿爾宙斯"],
        answer: 1,
        category: "深入配布",
    },
    {
        id: 46,
        question: "寶可夢 HOME 上贈送的特殊皮卡丘是什麼形態？",
        options: ["戴著原始帽的皮卡丘", "歌唱皮卡丘", "飛翔皮卡丘", "衝浪皮卡丘"],
        answer: 0,
        category: "深入配布",
    },
    {
        id: 47,
        question: "「七夕基拉祈」是透過什麼方式配布的？",
        options: ["Wi-Fi 下載", "寶可夢中心店面", "序號兌換", "七夕期間限定序號"],
        answer: 1,
        category: "深入配布",
    },
    {
        id: 48,
        question: "GameStop 在北美地區配布的寶可夢通常使用什麼方式？",
        options: ["網路下載", "序號卡", "紅外線", "NFC"],
        answer: 1,
        category: "深入配布",
    },
    {
        id: 49,
        question: "配布寶可夢通常會有鎖定，以下哪項不常被鎖定？",
        options: ["等級", "性格", "招式", "暱稱"],
        answer: 1,
        category: "深入配布",
    },
    {
        id: 50,
        question: "歷史上第一個正式配布的寶可夢是？",
        options: ["夢幻", "超夢", "皮卡丘", "小火龍"],
        answer: 0,
        category: "深入配布",
    },
    {
        id: 51,
        question: "劇場版配布中，「裝甲超夢」出現在哪部電影？",
        options: ["超夢的逆襲", "超夢的逆襲 EVOLUTION", "神速的蓋諾賽克特", "波導的勇者"],
        answer: 1,
        category: "深入配布",
    },
    {
        id: 52,
        question: "第四世代中，「會員卡」這個道具是用來遇見哪隻幻之寶可夢？",
        options: ["謝米", "達克萊伊", "阿爾宙斯", "瑪納霏"],
        answer: 1,
        category: "深入配布",
    },
    {
        id: 53,
        question: "第五世代中，「自由船票」是用來前往哪裡？",
        options: ["自由花園", "夢之遺跡", "冠軍之路", "螺旋山"],
        answer: 0,
        category: "深入配布",
    },
    {
        id: 54,
        question: "色違的寶可夢配布中，以下哪隻從未有過官方色違配布？",
        options: ["烈空坐", "固拉多", "蓋歐卡", "夢幻"],
        answer: 3,
        category: "深入配布",
    },
    {
        id: 55,
        question: "「世界錦標賽」歷屆冠軍獎品通常包含什麼？",
        options: ["限定主機", "配布寶可夢和獎盃", "遊戲開發權", "終身免費遊戲"],
        answer: 1,
        category: "深入配布",
    },

    // ========== 遊戲歷史 (15 題) ==========
    {
        id: 56,
        question: "寶可夢紅/綠版中著名的 Bug「MissingNo.」是什麼？",
        options: ["隱藏的傳說寶可夢", "程式錯誤產生的亂碼寶可夢", "開發者的彩蛋", "限定配布"],
        answer: 1,
        category: "遊戲歷史",
    },
    {
        id: 57,
        question: "第二世代中，與初代連動時使用的是什麼裝置？",
        options: ["通信線", "紅外線", "Wi-Fi", "藍牙"],
        answer: 0,
        category: "遊戲歷史",
    },
    {
        id: 58,
        question: "寶可夢水晶版是第一個加入什麼功能的寶可夢遊戲？",
        options: ["可選擇女性主角", "可連線對戰", "可交換寶可夢", "可自訂名稱"],
        answer: 0,
        category: "遊戲歷史",
    },
    {
        id: 59,
        question: "寶可夢 XD：暗之旋風中的主角機台是？",
        options: ["Game Boy Advance", "Nintendo DS", "GameCube", "Wii"],
        answer: 2,
        category: "遊戲歷史",
    },
    {
        id: 60,
        question: "第三世代中引入的「雙打對戰」最初出現在哪款遊戲？",
        options: ["紅寶石/藍寶石", "火紅/葉綠", "綠寶石", "競技場"],
        answer: 0,
        category: "遊戲歷史",
    },
    {
        id: 61,
        question: "寶可夢黑2/白2 是系列中罕見的什麼？",
        options: ["跨世代續作", "兩年後的正統續作", "重製版", "外傳作品"],
        answer: 1,
        category: "遊戲歷史",
    },
    {
        id: 62,
        question: "「寶可夢牧場」是哪個主機上的寶可夢寄存軟體？",
        options: ["Nintendo 64", "GameCube", "Wii", "Wii U"],
        answer: 2,
        category: "遊戲歷史",
    },
    {
        id: 63,
        question: "第五世代（黑/白）有什麼特殊之處？",
        options: ["全部使用新寶可夢，主線不含舊世代", "首次加入 3D 建模", "首次加入 Mega 進化", "首次加入妖精屬性"],
        answer: 0,
        category: "遊戲歷史",
    },
    {
        id: 64,
        question: "「寶可夢競技場」系列最早是在哪個主機上推出？",
        options: ["Super Famicom", "Nintendo 64", "GameCube", "Game Boy"],
        answer: 1,
        category: "遊戲歷史",
    },
    {
        id: 65,
        question: "寶可夢 GO 的開發商是？",
        options: ["Nintendo", "Game Freak", "Niantic", "The Pokémon Company"],
        answer: 2,
        category: "遊戲歷史",
    },
    {
        id: 66,
        question: "寶可夢傳說 阿爾宙斯的故事背景設定在什麼時代？",
        options: ["未來", "現代", "古代（明治時期前）", "平行世界"],
        answer: 2,
        category: "遊戲歷史",
    },
    {
        id: 67,
        question: "寶可夢紅/綠的原始圖鑑中有多少隻寶可夢？",
        options: ["130", "143", "150", "151"],
        answer: 3,
        category: "遊戲歷史",
    },
    {
        id: 68,
        question: "第四世代的物理/特殊分類改革是什麼？",
        options: ["屬性不再決定物理/特殊，改由招式個別決定", "所有招式變為特殊", "新增混合傷害類型", "取消屬性一致加成"],
        answer: 0,
        category: "遊戲歷史",
    },
    {
        id: 69,
        question: "寶可夢的第一款外傳遊戲是？",
        options: ["寶可夢競技場", "寶可夢隨樂拍", "寶可夢彈珠台", "寶可夢不可思議迷宮"],
        answer: 0,
        category: "遊戲歷史",
    },
    {
        id: 70,
        question: "寶可夢劍/盾的 DLC 名稱是什麼？",
        options: ["超越邊界", "鎧之孤島 & 冠之雪原", "蒼空的彼方", "星辰之路"],
        answer: 1,
        category: "遊戲歷史",
    },

    // ========== 數據細節 (15 題) ==========
    {
        id: 71,
        question: "所有寶可夢中種族值速度最高的是？",
        options: ["鐵束", "雷吉艾勒奇", "暴飛龍", "超夢"],
        answer: 1,
        category: "數據細節",
    },
    {
        id: 72,
        question: "招式「破壞光線」的威力是多少？",
        options: ["120", "130", "140", "150"],
        answer: 3,
        category: "數據細節",
    },
    {
        id: 73,
        question: "招式「地震」的威力與命中率分別是？",
        options: ["100/100", "90/100", "100/90", "120/85"],
        answer: 0,
        category: "數據細節",
    },
    {
        id: 74,
        question: "努力值（EV）全部六項的總上限是？",
        options: ["252", "382", "510", "600"],
        answer: 2,
        category: "數據細節",
    },
    {
        id: 75,
        question: "招式「龍星群」使用後會降低自身特攻幾階？",
        options: ["1 階", "2 階", "3 階", "不會降低"],
        answer: 1,
        category: "數據細節",
    },
    {
        id: 76,
        question: "精靈球的基本捕獲率是多少？",
        options: ["×0.5", "×1.0", "×1.5", "×2.0"],
        answer: 1,
        category: "數據細節",
    },
    {
        id: 77,
        question: "高級球的捕獲率是精靈球的多少倍？",
        options: ["1.0 倍", "1.5 倍", "2.0 倍", "2.5 倍"],
        answer: 1,
        category: "數據細節",
    },
    {
        id: 78,
        question: "招式「劍舞」可以將攻擊提升幾階？",
        options: ["1 階", "2 階", "3 階", "4 階"],
        answer: 1,
        category: "數據細節",
    },
    {
        id: 79,
        question: "寶可夢的能力值最多可以提升到幾階？",
        options: ["4 階", "5 階", "6 階", "8 階"],
        answer: 2,
        category: "數據細節",
    },
    {
        id: 80,
        question: "提升 6 階時，能力值變為原來的多少倍？",
        options: ["3 倍", "4 倍", "5 倍", "6 倍"],
        answer: 1,
        category: "數據細節",
    },
    {
        id: 81,
        question: "招式「暴風雪」的命中率是多少？",
        options: ["70%", "75%", "80%", "85%"],
        answer: 0,
        category: "數據細節",
    },
    {
        id: 82,
        question: "在冰雹天氣下，「暴風雪」的命中率變為？",
        options: ["85%", "90%", "95%", "100%（必中）"],
        answer: 3,
        category: "數據細節",
    },
    {
        id: 83,
        question: "招式「火焰放射」的威力是多少？",
        options: ["80", "85", "90", "95"],
        answer: 2,
        category: "數據細節",
    },
    {
        id: 84,
        question: "特性「沙之力」在沙暴中提升哪些屬性招式的威力？",
        options: ["地面、岩石、鋼", "地面、岩石、火", "岩石、鋼、暗", "地面、鋼、一般"],
        answer: 0,
        category: "數據細節",
    },
    {
        id: 85,
        question: "寶可夢的全部種族值總和最高是多少（不含 Mega 和原始回歸）？",
        options: ["680", "700", "720", "780"],
        answer: 2,
        category: "數據細節",
    },

    // ========== 伊布進階 (15 題) ==========
    {
        id: 86,
        question: "伊布的種族值總和是多少？",
        options: ["325", "355", "385", "405"],
        answer: 0,
        category: "伊布進階",
    },
    {
        id: 87,
        question: "所有伊布進化型中，種族值總和最高的是？",
        options: ["仙子伊布", "太陽伊布", "所有進化型都一樣", "水伊布"],
        answer: 2,
        category: "伊布進階",
    },
    {
        id: 88,
        question: "太陽伊布的最高種族值是哪個能力？",
        options: ["速度", "特攻", "特防", "HP"],
        answer: 1,
        category: "伊布進階",
    },
    {
        id: 89,
        question: "月亮伊布的最高種族值是哪個能力？",
        options: ["攻擊", "特攻", "防禦", "特防"],
        answer: 3,
        category: "伊布進階",
    },
    {
        id: 90,
        question: "水伊布的 HP 種族值是多少？",
        options: ["95", "110", "125", "130"],
        answer: 3,
        category: "伊布進階",
    },
    {
        id: 91,
        question: "火伊布的攻擊種族值在所有伊布進化型中排名如何？",
        options: ["最高", "第二高", "中等", "最低"],
        answer: 0,
        category: "伊布進階",
    },
    {
        id: 92,
        question: "仙子伊布在競技對戰中最常見的特性是？",
        options: ["魅惑之軀", "危險預知", "妖精皮膚", "適應力"],
        answer: 2,
        category: "伊布進階",
    },
    {
        id: 93,
        question: "伊布在 Pokémon GO 中，使用「花名」進化法能確保進化成葉伊布的名字是？",
        options: ["Sakura", "Linnea", "Tamao", "Rea"],
        answer: 1,
        category: "伊布進階",
    },
    {
        id: 94,
        question: "雷伊布的速度種族值是多少？",
        options: ["110", "120", "130", "140"],
        answer: 2,
        category: "伊布進階",
    },
    {
        id: 95,
        question: "冰伊布在競技對戰中較少被使用，主要原因是？",
        options: ["種族值太低", "冰屬性防禦面弱點多", "不能學會好招式", "特性太差"],
        answer: 1,
        category: "伊布進階",
    },
    {
        id: 96,
        question: "葉伊布的隱藏特性是什麼？",
        options: ["葉綠素", "葉子防守", "再生力", "收穫"],
        answer: 0,
        category: "伊布進階",
    },
    {
        id: 97,
        question: "月亮伊布可以學會招式「月光」，這個招式的效果是？",
        options: ["造成傷害", "回復 HP", "提升迴避率", "降低對手特防"],
        answer: 1,
        category: "伊布進階",
    },
    {
        id: 98,
        question: "仙子伊布的特性「妖精皮膚」會將什麼屬性的招式變為妖精屬性？",
        options: ["所有屬性", "一般屬性", "超能力屬性", "飛行屬性"],
        answer: 1,
        category: "伊布進階",
    },
    {
        id: 99,
        question: "太陽伊布的隱藏特性是什麼？",
        options: ["同步", "魔法鏡", "精神力", "預知夢"],
        answer: 1,
        category: "伊布進階",
    },
    {
        id: 100,
        question: "在第九世代中，伊布可以透過太晶化變成什麼屬性？",
        options: ["只能是一般屬性", "任何屬性", "只能是進化型的屬性", "不能太晶化"],
        answer: 1,
        category: "伊布進階",
    },
];

// 活動設定
export const EEVEE_DAY_CONFIG = {
    eventName: "伊步集點日",
    startDate: "2026-02-11T00:00:00+08:00",
    endDate: "2026-02-27T23:59:59+08:00",
    dailyAttempts: 1,
    questionsPerQuiz: 10,
    timePerQuestion: 15, // 秒
    passingScore: 7, // 答對 7 題算通過
    stampsRequired: 7, // 集滿 7 點可領取配布
    // 可選配布的篩選條件
    allowedPokemon: ["伊布", "蒂安希", "比克提尼"],
    allowedGenerations: [8, 9],
};
