-- 補上 check-in API 需要的欄位
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS points INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS lottery_tickets INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS blindbox_coupons INTEGER DEFAULT 0;
