-- Add the owner-provided Kiyu Eevee evolution records to the distribution dex.
-- These are site catalog entries that extend the existing Kiyu Eevee entry.

ALTER TABLE public.distributions
  ADD COLUMN IF NOT EXISTS pokemon_sprite_url TEXT,
  ADD COLUMN IF NOT EXISTS event_name TEXT,
  ADD COLUMN IF NOT EXISTS points INTEGER DEFAULT 0;

WITH source_rows AS (
  SELECT *
  FROM (
    VALUES
      (
        '水伊布',
        'Vaporeon',
        134,
        9,
        ARRAY['朱', '紫']::TEXT[],
        'Kiyu',
        NULL::TEXT,
        NULL::INTEGER,
        'Site catalog entry',
        DATE '2026-05-22',
        NULL::DATE,
        'Taiwan',
        FALSE,
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png',
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png',
        NULL::TEXT,
        'Kiyu 的水伊布',
        NULL::TEXT,
        5000
      ),
      (
        '雷伊布',
        'Jolteon',
        135,
        9,
        ARRAY['朱', '紫']::TEXT[],
        'Kiyu',
        NULL::TEXT,
        NULL::INTEGER,
        'Site catalog entry',
        DATE '2026-05-22',
        NULL::DATE,
        'Taiwan',
        FALSE,
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png',
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png',
        NULL::TEXT,
        'Kiyu 的雷伊布',
        NULL::TEXT,
        5000
      ),
      (
        '火伊布',
        'Flareon',
        136,
        9,
        ARRAY['朱', '紫']::TEXT[],
        'Kiyu',
        NULL::TEXT,
        NULL::INTEGER,
        'Site catalog entry',
        DATE '2026-05-22',
        NULL::DATE,
        'Taiwan',
        FALSE,
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png',
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png',
        NULL::TEXT,
        'Kiyu 的火伊布',
        NULL::TEXT,
        5000
      ),
      (
        '太陽伊布',
        'Espeon',
        196,
        9,
        ARRAY['朱', '紫']::TEXT[],
        'Kiyu',
        NULL::TEXT,
        NULL::INTEGER,
        'Site catalog entry',
        DATE '2026-05-22',
        NULL::DATE,
        'Taiwan',
        FALSE,
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/196.png',
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/196.png',
        NULL::TEXT,
        'Kiyu 的太陽伊布',
        NULL::TEXT,
        5000
      ),
      (
        '月亮伊布',
        'Umbreon',
        197,
        9,
        ARRAY['朱', '紫']::TEXT[],
        'Kiyu',
        NULL::TEXT,
        NULL::INTEGER,
        'Site catalog entry',
        DATE '2026-05-22',
        NULL::DATE,
        'Taiwan',
        FALSE,
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/197.png',
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/197.png',
        NULL::TEXT,
        'Kiyu 的月亮伊布',
        NULL::TEXT,
        5000
      ),
      (
        '葉伊布',
        'Leafeon',
        470,
        9,
        ARRAY['朱', '紫']::TEXT[],
        'Kiyu',
        NULL::TEXT,
        NULL::INTEGER,
        'Site catalog entry',
        DATE '2026-05-22',
        NULL::DATE,
        'Taiwan',
        FALSE,
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/470.png',
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/470.png',
        NULL::TEXT,
        'Kiyu 的葉伊布',
        NULL::TEXT,
        5000
      ),
      (
        '冰伊布',
        'Glaceon',
        471,
        9,
        ARRAY['朱', '紫']::TEXT[],
        'Kiyu',
        NULL::TEXT,
        NULL::INTEGER,
        'Site catalog entry',
        DATE '2026-05-22',
        NULL::DATE,
        'Taiwan',
        FALSE,
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/471.png',
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/471.png',
        NULL::TEXT,
        'Kiyu 的冰伊布',
        NULL::TEXT,
        5000
      ),
      (
        '仙子伊布',
        'Sylveon',
        700,
        9,
        ARRAY['朱', '紫']::TEXT[],
        'Kiyu',
        NULL::TEXT,
        NULL::INTEGER,
        'Site catalog entry',
        DATE '2026-05-22',
        NULL::DATE,
        'Taiwan',
        FALSE,
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/700.png',
        'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/700.png',
        NULL::TEXT,
        'Kiyu 的仙子伊布',
        NULL::TEXT,
        5000
      )
  ) AS t(
    pokemon_name,
    pokemon_name_en,
    pokemon_dex_number,
    generation,
    game_titles,
    original_trainer,
    trainer_id,
    level,
    distribution_method,
    distribution_period_start,
    distribution_period_end,
    region,
    is_shiny,
    pokemon_sprite_url,
    image_url,
    wiki_url,
    event_name,
    special_move,
    points
  )
)
INSERT INTO public.distributions (
  pokemon_name,
  pokemon_name_en,
  pokemon_dex_number,
  generation,
  game_titles,
  original_trainer,
  trainer_id,
  level,
  distribution_method,
  distribution_period_start,
  distribution_period_end,
  region,
  is_shiny,
  pokemon_sprite_url,
  image_url,
  wiki_url,
  event_name,
  special_move,
  points
)
SELECT
  pokemon_name,
  pokemon_name_en,
  pokemon_dex_number,
  generation,
  game_titles,
  original_trainer,
  trainer_id,
  level,
  distribution_method,
  distribution_period_start,
  distribution_period_end,
  region,
  is_shiny,
  pokemon_sprite_url,
  image_url,
  wiki_url,
  event_name,
  special_move,
  points
FROM source_rows s
WHERE NOT EXISTS (
  SELECT 1
  FROM public.distributions d
  WHERE d.pokemon_name_en = s.pokemon_name_en
    AND COALESCE(d.event_name, '') = COALESCE(s.event_name, '')
    AND COALESCE(d.original_trainer, '') = COALESCE(s.original_trainer, '')
    AND d.distribution_period_start IS NOT DISTINCT FROM s.distribution_period_start
);
